### PR TITLE
Fix writing contents to extra files. Fixes #44

### LINKED ISSUE #44: Extra files contents undefined
Today I tried uploading my settings with extra files defined. Aldo the files were created, the contents was `undefined`.

### PR DESCRIPTION
**Pull request by jerone**
Fixes https://github.com/Hackafe/atom-sync-settings/issues/44
Ref https://github.com/Hackafe/atom-sync-settings/pull/32

### CODE REVIEW

**Comment by jerone** [comment]
Bump :punch:

**Comment by kankaristo** [comment]
This bug just cleared a bunch of my config files. :(

Please merge this!

**Comment by kankaristo** [comment]
Also, since something similar might happen in the future (bugs always happen), would it be possible to make a local backup before overwriting a file? These could be stored in `~/.atom/sync-settings-backups`.

**Comment by groupsky** [comment]
:+1:

**Comment by groupsky** [comment]
@jerone can you add a spec for the bug, before merging?

**Comment by jerone** [comment]
Clean new PR in https://github.com/Hackafe/atom-sync-settings/pull/64

**Pull request closed without merging**
