### PR TITLE
Solve issue #36 (Snippets not applied)

### PR DESCRIPTION
**Pull request by almostearthling**
Changes the name of the downloaded gist file to `snippets.cson`.

F.

### CODE REVIEW

**Comment by jerone** [comment]
Good find! Can you add some specs for this, so it won't happen again.

We also need to be thinking about cleaning up old installs... we probably want to remove the redundant `snippets.coffee` file.

**Comment by almostearthling** [comment]
Well, I can try to add a test to check that uploaded and downloaded files are the same, as this was the case that would actually break the spec. As a matter of removing `snippets.coffee`, I don't know how it should be handled: adding code (and load time :smirk:) just to clean up the mess we've done could be overkill, unless we assume that this will be done by a fixed number of "transitional" releases.

However I don't know how long will it take to me to write the spec, maybe it's worth to fix the thing in order to get it running (a minor release) and add the full-fledged update when there are more features to add.

F.

**Comment by almostearthling** [comment]
I changed my mind: in the specs the test for snippets.cson is missing while the other ones are already there. I'll fix it ASAP.

F.

**Comment by jerone** [comment]
> However I don't know how long will it take to me to write the spec, maybe it's worth to fix the thing in order to get it running (a minor release) and add the full-fledged update when there are more features to add.

Just copy the specs from keymap.cson https://github.com/Hackafe/atom-sync-settings/blob/master/spec/sync-settings-spec.coffee#L84-L91

**Comment by almostearthling** [comment]
That's what I said above in fact, I thought I'd do something more complicated but there's no need to! :smiley: 

F.

**Comment by almostearthling** [comment]
Ok, Travis does not complain with the new spec.

F.

**Comment by jerone** [comment]
:+1:

**Comment by jerone** [comment]
Ref #36

**Pull request merged**
