### PR TITLE
Implement CoffeeLint 

### PR DESCRIPTION
**Pull request by jerone**
http://www.coffeelint.org

Should be run before submitting any new content: `coffeelint .`

### CODE REVIEW

**Comment by groupsky** [comment]
Is it run by travis?

**Comment by jerone** [comment]
[**@groupsky**](https://github.com/groupsky) commented on [23 jun. 2015 09:50 CEST](https://github.com/Hackafe/atom-sync-settings/pull/80#issuecomment-114395148 "2015-06-23T07:50:42Z - Replied by Github Comment Enhancer"):
> Is it run by travis?

Am not sure about that one. Will do a Google search...

**Comment by jerone** [comment]
How can I forget, yes it does: https://travis-ci.org/Hackafe/atom-sync-settings/builds/67956936#L108-L118 (sorry have to wake up).

**Comment by groupsky** [comment]
in that case :+1:

**Pull request merged**
